### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [zahmryan/my_new_app#1]
This looks really good. There are just a one thing I'd like you to update: 
- I see [a four-space tab here](https://github.com/zahmryan/my_new_app/blob/master/app/views/static/cats.html.erb#L2). I know, it's nit-picky, but these little missed details can add up quickly in a growing project.
- [This way of calling a method in Ruby](https://github.com/zahmryan/my_new_app/blob/master/app/views/static/home.html.erb#L3) is actually overly verbose. Instead of `current_date_and_time();`, you can just write `current_date_and_time`. The parentheses are optional (even when a method has parameters) and the `;` is only necessary to combine multiple lines of Ruby into a single line.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by zahmryan** [comment]
I changed that line to a 2 space tab, and removed the parentheses on the method call!

**Comment by chrisvfritz** [comment]
:+1: Much better!
